### ISSUE TITLE
Warning on macOS

### ISSUE THREAD

**Issue by jserv** [jart/blink#1]
I attempted to build `blink` on macOS, and `make` complained as following:
> blink/random.c:71:9: error: implicit declaration of function 'getentropy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

It can be resolved by a straightforward change:
```diff
diff --git a/blink/random.c b/blink/random.c
index 0be6c04..d94bf3e 100644
--- a/blink/random.c
+++ b/blink/random.c
@@ -30,6 +30,9 @@
 #include <sys/sysctl.h>
 #include <sys/types.h>
 #endif
+#if defined(__APPLE__)
+#include <sys/random.h>
+#endif
 #include "blink/assert.h"
 #include "blink/errno.h"
 #include "blink/random.h"
```

**Comment by jart** [comment]
Thanks for spotting this! Fixing right now.
