### ISSUE TITLE
Consider using "basic block" optimization technique

### ISSUE THREAD

**Issue by safinaskar** [jart/blink#113]
Consider using optimization technique described here:
- https://blog.reverberate.org/2021/04/21/musttail-efficient-interpreters.html
- https://sillycross.github.io/2022/11/22/2022-11-22/index.html

for instruction decoder. This is technique, which applies to all algorithms, which can be somehow described as "instruction decoders", i. e. decompressors, bytecode interpreters, parsers, etc.

Also possibly related https://blog.reverberate.org/2020/05/29/hoares-rebuttal-bubble-sorts-comeback.html

**Comment by jart** [comment]
I've used the tail call interpreter technique in the past for Plinko, which is a LISP dialect I wrote a year ago. https://github.com/jart/cosmopolitan/blob/4a6be2154d029f2859a6d17cbba7f8ddce94e044/tool/plinko/lib/plinko.c#L390 It makes the code so much more elegant. It goes much faster than "one big switch" and much faster than "computed goto". Especially if you use the x86 segment registers to create a shadow space of shortcut dispatch paths. Doing that yielded a LISP interpreter that's almost as fast as a JIT'ing LISP like SBCL. 

```
BENCHMARK

  binary trees (n=21)

    - sbcl:     200 ms (native jit;  simulated arithmetic)
    - plinko:   400 ms (interpreted; simulated arithmetic)
    - python3:  800 ms (interpreted;    native arithmetic)
    - racket:  1200 ms (interpreted; simulated arithmetic)
```

I'm not sure how much Blink would benefit from this. Blink has a JIT so instruction decoding is an amortized cost. It'd help the non-JIT architectures if we did this, like PowerPC and RISC-V. But I'd honestly rather just do the ~5 things needed to make them JIT properly. All I need to add JIT support for an architecture is for someone to donate a computer to the project that I can own and SSH into. Blink only hand-codes a few simple instructions in assembly. Everything else is C.

Thank you for the suggestion though! I'm going to close this out as considered. Feel free to keep discussing!
