### ISSUE TITLE
Four errors occurred while making.

### ISSUE THREAD

**Issue by Ender-ren-small** [jart/blink#12]
./blink/termios.h:9:16: error: ‘TIOCSETA’ undeclared (first use in this function); did you mean ‘TIOCMSET’?
    9 | #define TCSETS TIOCSETA
      |                ^~~~~~~~
./blink/termios.h:6:16: error: ‘TIOCGETA’ undeclared (first use in this function); did you mean ‘TIOCMGET’?
    6 | #define TCGETS TIOCGETA
      |                ^~~~~~~~
./blink/termios.h:12:17: error: ‘TIOCSETAW’ undeclared (first use in this function); did you mean ‘TCSETAW’?
   12 | #define TCSETSW TIOCSETAW
      |                 ^~~~~~~~~
./blink/termios.h:15:17: error: ‘TIOCSETAF’ undeclared (first use in this function); did you mean ‘TCSETAF’?
   15 | #define TCSETSF TIOCSETAF
      |                 ^~~~~~~~~

**Comment by jart** [comment]
What operating system / platform are you using?

**Comment by JoshuaWierenga** [comment]
@Ender-ren-small This should be fixed now that blink doesn't use those ioctl constants. Does it work for you?

**Comment by jart** [comment]
Marking as fixed.
