### ISSUE TITLE
Discord invite expired

### ISSUE THREAD

**Issue by unconed** [jart/blink#143]
The Discord link mentioned in the 1.0 release announcement doesn't seem to work:
https://discord.gg/HQNA9faw

Via: https://github.com/jart/blink/releases

**Comment by jart** [comment]
Hey @lonnietc and @unconed. The latest invite code to our Discord is https://discord.gg/TaXpcekw Hope to see you both there! If anyone needs another invite code after this one expires in seven days, feel free to ping this issue or email jtunney@gmail.com
