### ISSUE TITLE
BIOS plis 🥺

### ISSUE THREAD

**Issue by 0xhiro** [jart/blink#15]
I would like to test some tiny bootloaders with blink. Any future plans for bios support or is this  already supported?

**Comment by 0xhiro** [comment]
Opps! wrong repo!

**Comment by tkchia** [comment]
Hello @0xhiro,

The `o/blink/blinkenlights` debugger user interface can already run BIOS disk images.  The disk image file name needs to end with a `.bin` extension.

Thank you!

**Comment by jart** [comment]
Indeed. Although I just ran `./blinkenlights -r sectorlisp.bin` to confirm. It looks like recent changes may have introduced regressions in the real mode support, so you might need to rewind history a bit to use BIOS. Sorry! It'll be fixed soon.

**Comment by 0xhiro** [comment]
VERY COOL!

**Comment by jart** [comment]
I believe I've fixed most of the issues with the real mode emulation TUI. https://github.com/jart/blink/commit/3887253c3f1c52753789dc50b7c72c0d0cacf9eb I've also written a tutorial on how to emulate real mode programs like SectorLISP here: https://github.com/jart/blink/tree/master/third_party/sectorlisp See also https://justine.lol/blinkenlights/realmode.html

**Comment by 0xhiro** [comment]
That's Awesome! Thanks for the quick fix. I believe i should be able to run an open source BIOS like [coreboot](https://www.coreboot.org/downloads.html). But i don't think it would work because there are no provisions for required virtualized hardware like a screen for it to run. My goal is to run a tiny operating system with Blink like i would do with QEMU.

**Comment by jart** [comment]
SectorLISP is something I'd consider to be a tiny operating system 😄

**Comment by 0xhiro** [comment]
Forgive me for not knowing much about sectorlisp, looks like it's the smallest lisp interpreter ever made.

**Comment by 0xhiro** [comment]
However, what i am referring to is virtualized hardware that operating systems can use to boot and run. Like screen serial, keyboard, networking etc. Are these planned to be implemented?

**Comment by 0xhiro** [comment]
And are pull requests welcome in that area?

**Comment by jart** [comment]
It is. Read my blog post https://justine.lol/sectorlisp2/ Pull requests are welcome but I must warn you it's not an easy project to improve upon.

We currently haven't allocated any resources towards virtualizing hardware, other than the x86 CPU itself. The focus has been more towards virtualizing the Linux Kernel ABI.

**Comment by 0xhiro** [comment]
It's okay to allow the project to proceed in it's current trajectory. It's probably too early to allocate efforts towards peripherals, but i'm glad that it is at least planned, right?

**Comment by ghaerr** [comment]
Hello @0xhiro,

Due to the complexity of emulating the variety of possible hardware devices, it's a lot of work to implement this and keep the emulator small, and QEMU already does a lot of that. For tiny real mode-only emulation, there are some good options available, if using BIOS INT 10h (video), BDA (BIOS Data Area), INT 13h (disk), and EGA/VGA text mode emulation directly writing to segment B800h will work for your needs. For instance, [EMU86](https://github.com/ghaerr/emu86) emulates 8086 only and implements these routines, and will run with streaming text (terminal emulator) output, or with an EGA/VGA text mode console using SDL.

Thank you!
