### ISSUE TITLE
Versioning scheme for GitHub releases

### ISSUE THREAD

**Issue by timsutton** [jart/blink#164]
👋 Hi! I was recently [updating Blink's formula in Homebrew](https://github.com/Homebrew/homebrew-core/pull/160555#discussion_r1461071319). I noticed that versioning is tagged in an x.y.z form both in the binary and in Git tags, but that the GitHub releases are just versioned as x.y. Is there any particular reason to use a different version number in the release/asset vs. the git repo's tags?

**Comment by jart** [comment]
I can change it.

**Comment by jart** [comment]
Done. Thanks for packaging Blink!
