### ISSUE TITLE
Support loading static-pie executables

### ISSUE THREAD

**Issue by Vogtinator** [jart/blink#36]
It's possible to build statically linked position-independent ELF binaries which can benefit from ASLR for instance.
Those are represented as `ET_DYN` type objects but unlike dynamically linked executables they don't have any `PT_INTERP` set.

They can be loaded like executables, they just need to be loaded at a (page-aligned) offset in VA space.

I put a dirty hack together:

```diff
diff --git a/blink/loader.c b/blink/loader.c
index e1cb048bb646..0afa4abb02d1 100644
--- a/blink/loader.c
+++ b/blink/loader.c
@@ -46,7 +46,7 @@ static i64 LoadElfLoadSegment(struct Machine *m, void *image, size_t imagesize,
   i64 bulk;
   struct System *s = m->system;
   u32 flags = Read32(phdr->p_flags);
-  i64 vaddr = Read64(phdr->p_vaddr);
+  i64 vaddr = Read64(phdr->p_vaddr) + 0x42000;
   i64 memsz = Read64(phdr->p_memsz);
   i64 offset = Read64(phdr->p_offset);
   i64 filesz = Read64(phdr->p_filesz);
@@ -188,8 +188,7 @@ bool IsSupportedExecutable(const char *path, void *image) {
   Elf64_Ehdr_ *ehdr;
   if (READ32(image) == READ32("\177ELF")) {
     ehdr = (Elf64_Ehdr_ *)image;
-    return Read16(ehdr->e_type) == ET_EXEC_ &&
-           ehdr->e_ident[EI_CLASS_] == ELFCLASS64_ &&
+    return ehdr->e_ident[EI_CLASS_] == ELFCLASS64_ &&
            Read16(ehdr->e_machine) == EM_NEXGEN32E_;
   }
   return READ64(image) == READ64("MZqFpD='") ||  //
@@ -216,7 +215,7 @@ static bool LoadElf(struct Machine *m, struct Elf *elf, int fd) {
   Elf64_Phdr_ *phdr;
   i64 end = INT64_MIN;
   bool execstack = true;
-  m->ip = elf->base = Read64(elf->ehdr->e_entry);
+  m->ip = elf->base = Read64(elf->ehdr->e_entry) + 0x42000;
   for (i = 0; i < Read16(elf->ehdr->e_phnum); ++i) {
     phdr = GetElfSegmentHeaderAddress(elf->ehdr, elf->size, i);
     switch (Read32(phdr->p_type)) {
```

**Comment by jart** [comment]
You would only be able to apply that skew after checking it's `ET_DYN` otherwise you'd break normal executables. PIE executables also require that the loader apply relocation fixups from the DYNAMIC program section. Blink doesn't have that currently, which is one of the big things blocking https://github.com/jart/blink/issues/7

**Comment by Vogtinator** [comment]
> You would only be able to apply that skew after checking it's ET_DYN otherwise you'd break normal executables.

Yup, which is one of the reasons why that diff is just a dirty hack.

> PIE executables also require that the loader apply relocation fixups from the DYNAMIC program section. Blink doesn't have that currently, which is one of the big things blocking https://github.com/jart/blink/issues/7

AFAIK (but I'm not entirely sure, there's not much info available) only PIE, but not static-pie. The latter are fully position independent and expected to apply relocations themselves if necessary. With the hack applied I can call bash from the host:

```
> o/blink/blink /lib64/ld-linux-x86-64.so.2 /bin/bash -c 'echo "Hi"'
I2023-01-18T19:19:11.815727:blink/syscall.c:3366:8968 missing syscall 0x14e
Hi
```

**Comment by jart** [comment]
This issue has been solved in https://github.com/jart/blink/commit/8a4edae3e1a3896c861577f1b5de9b5d6761cb67

**Comment by Vogtinator** [comment]
Does not work, neither loading dynamically linked binaries:

```
> o/blink/blink /usr/bin/true
I2023-01-20T15:28:43.296416:blink/memorymalloc.c:528:12523 mmap(0x400000[0x400000], 0x1000) crisis: requested memory overlapped blink image or system memory
unrecoverable mmap() crisis: see log for further details
```

Nor the dynamic loader itself:

```
> o/blink/blink /lib64/ld-linux-x86-64.so.2 --help
I2023-01-20T15:27:45.191023:blink/memorymalloc.c:528:12430 mmap(0x400000[0x400000], 0x1000) crisis: requested memory overlapped blink image or system memory
unrecoverable mmap() crisis: see log for further detail
```

**Comment by Vogtinator** [comment]
Can be easily reproduced with any static-pie here:

```sh
> echo "int main(){}" > test.c && cc -static-pie test.c -o testpie
> ./testpie
> o/blink/blink ./testpie
I2023-01-20T15:30:14.018065:blink/memorymalloc.c:528:12585 mmap(0x400000[0x400000], 0xc000) crisis: requested memory overlapped blink image or system memory
unrecoverable mmap() crisis: see log for further details
```

**Comment by Vogtinator** [comment]
It looks like blink tries to load the linker at the same place as blink. If I build blink as PIE, it's loaded at a random address and it works.

I bisected that and it's actually caused by the changes in 669e511c93896154c22a9e14297bbba74d6ecefb.
Before that commit, for instance `busybox-static` was loaded at `88800400000`. Now it tries to load it at `400000`, which is also the default address of `blink` itself.

**Comment by jart** [comment]
I've configured the build to explicitly enable pie by default. There's also more helpful information that will be printed now when there's an mmap() crisis.

**Comment by Vogtinator** [comment]
> I've configured the build to explicitly enable pie by default.

You'll have to pass `-pie` in `LDFLAGS` as well, currently the objects are PIE but the executable still static
