### ISSUE TITLE
getdents() is buggy

### ISSUE THREAD

**Issue by faliagas** [jart/blink#6]
I tried to compile blink on a raspberry pi 4 with the command
`build/bootstrap/blink-linux-aarch64 build/bootstrap/make.com -j8 o//blink/blink`
but it failed with the error message
`make.com: *** INTERNAL: readdir: EINVAL/22/Invalid argument.  Stop.`

My OS is Ubuntu 22.10
Gcc version: 12.2.0

**Comment by jart** [comment]
This might have already been fixed at head. Chances are the `make` command that comes with your RasPi distro is already good enough to build this repository. Try using vanilla make on RasPi4. That's what I do.
