### ISSUE TITLE
compilation issue under MacOS 13.2

### ISSUE THREAD

**Issue by andreasfink** [jart/blink#63]
cc -g -O2 -fpie -fno-ident -fno-common -fstrict-aliasing -fstrict-overflow -pthread -U_FORTIFY_SOURCE -Werror -Wno-unused-parameter -Wno-missing-field-initializers -fsanitize=undefined -isystem third_party/zlib -iquote. -D_FILE_OFFSET_BITS=64 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -D__BSD_VISIBLE -DDEBUG -DNOJIT -DUBSAN  -c -o o/ubsan/blink/syscall.o blink/syscall.c
blink/syscall.c:1685:43: error: invalid application of 'sizeof' to an incomplete type 'struct ucred'
            m, calloc(1, CMSG_SPACE(sizeof(*ucred)))))) {
                                          ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:685:94: note: expanded from macro 'CMSG_SPACE'
#define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/arm/_param.h:21:78: note: expanded from macro '__DARWIN_ALIGN32'
#define       __DARWIN_ALIGN32(p)       ((__darwin_size_t)((__darwin_size_t)(p) + __DARWIN_ALIGNBYTES32) &~ __DARWIN_ALIGNBYTES32)
                                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
blink/syscall.c:1688:35: error: invalid application of 'sizeof' to an incomplete type 'struct ucred'
  cmsg->cmsg_len = CMSG_LEN(sizeof(*ucred));
                                  ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:686:78: note: expanded from macro 'CMSG_LEN'
#define CMSG_LEN(l)             (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + (l))
                                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
blink/syscall.c:1690:21: error: use of undeclared identifier 'SCM_CREDENTIALS'
  cmsg->cmsg_type = SCM_CREDENTIALS;
                    ^
blink/syscall.c:1692:8: error: incomplete definition of type 'struct ucred'
  ucred->pid = Read32(ucred_linux->pid);
  ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
blink/syscall.c:1693:8: error: incomplete definition of type 'struct ucred'
  ucred->uid = Read32(ucred_linux->uid);
  ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
blink/syscall.c:1694:8: error: incomplete definition of type 'struct ucred'
  ucred->gid = Read32(ucred_linux->gid);
  ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
blink/syscall.c:1696:42: error: invalid application of 'sizeof' to an incomplete type 'struct ucred'
  msg->msg_controllen = CMSG_SPACE(sizeof(*ucred));
                                         ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:685:94: note: expanded from macro 'CMSG_SPACE'
#define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/arm/_param.h:21:78: note: expanded from macro '__DARWIN_ALIGN32'
#define       __DARWIN_ALIGN32(p)       ((__darwin_size_t)((__darwin_size_t)(p) + __DARWIN_ALIGNBYTES32) &~ __DARWIN_ALIGNBYTES32)
                                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/file.h:77:8: note: forward declaration of 'struct ucred'
struct ucred;
       ^
7 errors generated.
make: *** [o/ubsan/blink/syscall.o] Error 1

**Comment by jart** [comment]
Sorry about that! Fixing it right now.

**Comment by jart** [comment]
It looked like another breakage slipped in with another change. I've confirmed on both MacOS Arm and MacOS x86 computers that `make check` is fully passing.

**Comment by jart** [comment]
As of change https://github.com/jart/blink/commit/d4d073ea1b99b1de879fc6f957d56ca2c083715a
