### ISSUE TITLE
unable to compile master on macOS after VFS support

### ISSUE THREAD

**Issue by latedeployment** [jart/blink#80]
Running macOS m2 13.0.1 

checkout out latest _master_ branch (current commit 8609bda5e3a56774e6c8112d8f354c1bee6be1f3)

Run:

`./configure && gmake`

Failure occurs: 
```
T_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -iquote.  -c -o o//blink/pipe.o blink/pipe.c
blink/pipe.c:57:7: error: implicit declaration of function 'VfsPipe' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (VfsPipe(fds) != -1) {
      ^
1 error generated.
```

If running  `./configure --enable-vfs && gmake`

Failure occurs as `fexecve` is not supported on mac. 

`
T_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -iquote.  -c -o o//blink/hostfs.o blink/hostfs.c
blink/hostfs.c:1840:10: error: implicit declaration of function 'fexecve' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return fexecve(hostinfo->filefd, argv, envp);
         ^
blink/hostfs.c:1840:10: note: did you mean 'execve'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:445:6: note: 'execve' declared here
int      execve(const char * __file, char * const * __argv, char * const * __envp) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
`

If running `./configure --posix && gmake`

`o//blink/ancillary.o blink/ancillary.c
blink/ancillary.c:55:29: error: implicit declaration of function 'CMSG_SPACE' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (msg->msg_controllen + CMSG_SPACE(size) > kMaxAncillary) {
                            ^
blink/ancillary.c:60:20: error: implicit declaration of function 'CMSG_LEN' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  cmsg->cmsg_len = CMSG_LEN(size);
                   ^
2 errors generated.`

**Comment by jart** [comment]
I'm going to push a change fixing the build errors relating to VFS.

As for `./configure --posix` on Darwin, contributions are welcome. You might want to consider using the `--disable-nonposix` flag for testing your apps, since the prior is intended more for testing the blink codebase internals.

**Comment by jart** [comment]
OK that one is solved. The rest of the errors are huge amounts of missing type errors. I don't intend to solve that right now because it looks like Darwin's headers are pretty busted. Contributions are welcome from anyone who knows why that happens.
