### ISSUE TITLE
Incorrect instructions in README.md ("o///blink/tui")

### ISSUE THREAD

**Issue by qroq** [jart/blink#9]
"build/bootstrap/make.com -j8 o///blink/tui"

At least for me, this 3-slash version doesn't actually build tui.
"o//blink/tui" works just fine.

**Comment by jart** [comment]
Thanks for bringing this to our attention. That's a typo I made. It should only have two slashes, i.e. `o//blink/tui`. I'll push a change shortly that corrects the readme file.
